export const NXD_PROTOCOL_ABI = [
  {
    'type': 'constructor',
    'inputs': [
      { 'name': 'initialSupply', 'type': 'uint256', 'internalType': 'uint256' },
      { 'name': '_dbxen', 'type': 'address', 'internalType': 'address' },
      { 'name': '_dbxenViews', 'type': 'address', 'internalType': 'address' },
      { 'name': '_v3Oracle', 'type': 'address', 'internalType': 'address' },
      { 'name': '_governance', 'type': 'address', 'internalType': 'address' },
      { 'name': '_devFeeTo', 'type': 'address', 'internalType': 'address' },
      {
        'name': '_devAllocMinter',
        'type': 'address',
        'internalType': 'address',
      },
    ],
    'stateMutability': 'nonpayable',
  },
  { 'type': 'receive', 'stateMutability': 'payable' },
  {
    'type': 'function',
    'name': 'DEADBEEF',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'DXN_WETH_POOL',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'UNISWAP_V2_FACTORY',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'UNISWAP_V2_ROUTER',
    'inputs': [],
    'outputs': [
      {
        'name': '',
        'type': 'address',
        'internalType': 'contract IUniswapV2Router02',
      },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'UNISWAP_V3_ROUTER',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract ISwapRouter' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'WETH9',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'collectFees',
    'inputs': [],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'createPool',
    'inputs': [
      { 'name': 'nxdDesired', 'type': 'uint256', 'internalType': 'uint256' },
      { 'name': 'dxnDesired', 'type': 'uint256', 'internalType': 'uint256' },
      { 'name': 'to', 'type': 'address', 'internalType': 'address' },
      { 'name': 'deadline', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'outputs': [
      { 'name': 'liquidity', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'currentRate',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'dbxen',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract IDBXen' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'dbxenViews',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract IDBXenViews' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'decreasePerSecond',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'deposit',
    'inputs': [
      { 'name': '_amount', 'type': 'uint256', 'internalType': 'uint256' },
      { 'name': '_referralCode', 'type': 'uint256', 'internalType': 'uint256' },
      { 'name': '_allowDynamicAmount', 'type': 'bool', 'internalType': 'bool' },
    ],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'depositNoMint',
    'inputs': [
      { 'name': '_amount', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'devAllocMinter',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'dxn',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract IERC20' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'endTime',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'getReferralBonuses',
    'inputs': [
      { 'name': 'amount', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'outputs': [
      {
        'name': 'referrerAmount',
        'type': 'uint256',
        'internalType': 'uint256',
      },
      { 'name': 'userAmount', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'stateMutability': 'pure',
  },
  {
    'type': 'function',
    'name': 'mintDevAlloc',
    'inputs': [
      {
        'name': 'recipients',
        'type': 'address[]',
        'internalType': 'address[]',
      },
    ],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'nxd',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract NXDERC20' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'nxdStakingVault',
    'inputs': [],
    'outputs': [
      {
        'name': '',
        'type': 'address',
        'internalType': 'contract NXDStakingVault',
      },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'ourClaimableFees',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'pendingDXNToStake',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'referralCodes',
    'inputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'outputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'referredRewards',
    'inputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'referrerRewards',
    'inputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'setDevAllocMinter',
    'inputs': [
      {
        'name': 'newDevAllowMinter',
        'type': 'address',
        'internalType': 'address',
      },
    ],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'setReferralCode',
    'inputs': [
      { 'name': '_referralCode', 'type': 'uint256', 'internalType': 'uint256' },
    ],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'stakeOurDXN',
    'inputs': [],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'function',
    'name': 'startTime',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalDXNBurned',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalDXNDepositedLMP',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalDXNStaked',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalETHToStakingVault',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalNXDBurned',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'totalUnclaimedReferralRewards',
    'inputs': [],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'userToReferralCode',
    'inputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'userTotalMintedNoBonus',
    'inputs': [{ 'name': '', 'type': 'address', 'internalType': 'address' }],
    'outputs': [{ 'name': '', 'type': 'uint256', 'internalType': 'uint256' }],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'v2Oracle',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract V2Oracle' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'v3Oracle',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract IV3Oracle' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'vesting',
    'inputs': [],
    'outputs': [
      { 'name': '', 'type': 'address', 'internalType': 'contract Vesting' },
    ],
    'stateMutability': 'view',
  },
  {
    'type': 'function',
    'name': 'withdrawReferralRewards',
    'inputs': [],
    'outputs': [],
    'stateMutability': 'nonpayable',
  },
  {
    'type': 'event',
    'name': 'Deposit',
    'inputs': [
      {
        'name': 'from',
        'type': 'address',
        'indexed': true,
        'internalType': 'address',
      },
      {
        'name': 'amount',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'amountReceived',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'referralCode',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
    ],
    'anonymous': false,
  },
  {
    'type': 'event',
    'name': 'HandleRewards',
    'inputs': [
      {
        'name': 'ethReceived',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'dxnAmountReceived',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'dxnBurned',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'dxnToStake',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'nxdBurned',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'ethToStakingVault',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
    ],
    'anonymous': false,
  },
  {
    'type': 'event',
    'name': 'PoolCreated',
    'inputs': [
      {
        'name': 'uniswapV2Pair',
        'type': 'address',
        'indexed': false,
        'internalType': 'address',
      },
      {
        'name': 'nxdDesired',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'dxnDesired',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
    ],
    'anonymous': false,
  },
  {
    'type': 'event',
    'name': 'ReferralCodeSet',
    'inputs': [
      {
        'name': 'referralCode',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
      {
        'name': 'user',
        'type': 'address',
        'indexed': true,
        'internalType': 'address',
      },
    ],
    'anonymous': false,
  },
  {
    'type': 'event',
    'name': 'ReferralRewardsWithdrawn',
    'inputs': [
      {
        'name': 'user',
        'type': 'address',
        'indexed': true,
        'internalType': 'address',
      },
      {
        'name': 'amount',
        'type': 'uint256',
        'indexed': false,
        'internalType': 'uint256',
      },
    ],
    'anonymous': false,
  },
  { 'type': 'error', 'name': 'CSPHasEnded', 'inputs': [] },
  { 'type': 'error', 'name': 'CSPOngoing', 'inputs': [] },
  { 'type': 'error', 'name': 'GotNothing', 'inputs': [] },
  { 'type': 'error', 'name': 'InvalidAmount', 'inputs': [] },
  { 'type': 'error', 'name': 'InvalidReferralCode', 'inputs': [] },
  { 'type': 'error', 'name': 'NXDMaxSupplyMinted', 'inputs': [] },
  { 'type': 'error', 'name': 'NoAutoReferral', 'inputs': [] },
  { 'type': 'error', 'name': 'NoRewards', 'inputs': [] },
  { 'type': 'error', 'name': 'NotAuthorized', 'inputs': [] },
  { 'type': 'error', 'name': 'NotInitialized', 'inputs': [] },
  { 'type': 'error', 'name': 'PoolAlreadyCreated', 'inputs': [] },
  { 'type': 'error', 'name': 'ReferralCodeAlreadySet', 'inputs': [] },
  { 'type': 'error', 'name': 'SendETHFail', 'inputs': [] },
] as const;
